import re
from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.enum.text import MSO_AUTO_SIZE, PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.xmlchemy import OxmlElement
import requests
from io import BytesIO
from PIL import Image

STYLES = {
    "Geometric": {
        "bg_start": (20, 20, 40),
        "bg_end": (40, 60, 100),
        "title_color": (100, 200, 255),
        "accent_color": (150, 200, 255),
        "text_color": (220, 220, 240),
        "shape_bg": (30, 50, 80),
        "has_shapes": False,
        "has_lines": True,
        "font": "Poppins",
    },
    "PlainText": {
        "bg_start": (255, 255, 255),
        "bg_end": (255, 255, 255),
        "title_color": (0, 0, 0),
        "accent_color": (100, 100, 100),
        "text_color": (0, 0, 0),
        "shape_bg": (255, 255, 255),
        "has_shapes": False,
        "has_lines": False,
        "font": "Poppins",
    }
}

def createPresentation(groq_content, output_filename, style="Geometric"):
    style_config = STYLES.get(style, STYLES["Geometric"])
    prs = Presentation()
    blank_layout = prs.slide_layouts[6]
    sections = re.split(r"(?=\*\*.*?\*\*)", groq_content.strip())
   
    def set_font(run, size, bold=False, color=None):
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.name = style_config["font"]
        if color:
            run.font.color.rgb = RGBColor(*color)

    def add_gradient_background(slide):
        background = slide.background
        fill = background.fill
        fill.gradient()
        fill.gradient_stops[0].color.rgb = RGBColor(*style_config["bg_start"])
        fill.gradient_stops[1].color.rgb = RGBColor(*style_config["bg_end"])

    def add_title_slide(title_text):
        slide = prs.slides.add_slide(blank_layout)
        add_gradient_background(slide)

        title_box = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(2))
        title_tf = title_box.text_frame
        p = title_tf.paragraphs[0]
        run = p.add_run()
        run.text = title_text
        set_font(run, 48, bold=True, color=style_config["title_color"])
        p.alignment = PP_ALIGN.CENTER

        if style_config["has_lines"]:
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1), Inches(4), Inches(8), Inches(0.05))
            line.fill.solid()
            line.fill.fore_color.rgb = RGBColor(*style_config["title_color"])
            line.line.fill.background()

        subtitle_box = slide.shapes.add_textbox(Inches(1), Inches(4.2), Inches(8), Inches(1))
        subtitle_tf = subtitle_box.text_frame
        p = subtitle_tf.paragraphs[0]
        run = p.add_run()
        run.text = "Generated by Socrates.vercel.app"
        set_font(run, 24, color=style_config["accent_color"])
        p.alignment = PP_ALIGN.CENTER

        if style_config["has_shapes"]:
            shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(3), Inches(5), Inches(4), Inches(1))
            shape.fill.solid()
            shape.fill.fore_color.rgb = RGBColor(*style_config["shape_bg"])
            shape.line.color.rgb = RGBColor(*style_config["accent_color"])
            shape.line.width = Pt(1)
            tf = shape.text_frame
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = "Powered by openai/gpt-oss-120b"
            set_font(run, 18, color=style_config["accent_color"])
            p.alignment = PP_ALIGN.CENTER

        slide_number_box = slide.shapes.add_textbox(Inches(9), Inches(6.8), Inches(1), Inches(0.5))
        slide_number_tf = slide_number_box.text_frame
        p = slide_number_tf.paragraphs[0]
        run = p.add_run()
        run.text = "1"
        set_font(run, 12, color=style_config["accent_color"])
        p.alignment = PP_ALIGN.RIGHT

    def add_content_slide(title, body_text, slide_index):
        slide = prs.slides.add_slide(blank_layout)
        add_gradient_background(slide)

        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(1))
        title_tf = title_box.text_frame
        p = title_tf.paragraphs[0]
        run = p.add_run()
        run.text = title
        set_font(run, 36, bold=True, color=style_config["title_color"])

        if style_config["has_lines"]:
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.5), Inches(1.3), Inches(9), Inches(0.05))
            line.fill.solid()
            line.fill.fore_color.rgb = RGBColor(*style_config["accent_color"])
            line.line.fill.background()

        text_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(5), Inches(5.8))
        text_tf = text_box.text_frame

        text_tf.word_wrap = True

        paragraphs = [para.strip() for para in body_text.split("•") if para.strip()]
        for para_text in paragraphs:
            p = text_tf.add_paragraph()
            run = p.add_run()
            run.text = f"• {para_text}"
            set_font(run, 22, bold=True, color=style_config["text_color"])

        if style_config["has_shapes"]:
            footer_shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(6.5), Inches(10), Inches(0.5))
            footer_shape.fill.solid()
            footer_shape.fill.fore_color.rgb = RGBColor(*style_config["shape_bg"])
            footer_shape.line.fill.background()
        else:
            footer_shape = slide.shapes.add_textbox(Inches(0), Inches(6.5), Inches(10), Inches(0.5))

        tf = footer_shape.text_frame if not style_config["has_shapes"] else footer_shape.text_frame
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text ="~ generated by Socrates.vercel.app    "
        set_font(run, 12, color=style_config["accent_color"])
        p.alignment = PP_ALIGN.RIGHT

    title_match = re.match(r"\*\*(.*?)\*\*", sections[0].strip())
    if title_match:
        add_title_slide(title_match.group(1).strip())
        sections = sections[1:]

    for i, section in enumerate(sections):
        match = re.match(r"\*\*(.*?)\*\*\s*(.*)", section.strip(), re.DOTALL)
        if match:
            title = match.group(1).strip()
            body_text = match.group(2).strip()
            add_content_slide(title, body_text, i)

    prs.save(output_filename)
